services:
  - type: worker
    name: firebase-ml-listener
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python firebase_listener.py
    envVars:
      - key: FIREBASE_KEY_JSON
        value: YOUR_JSON_STRING   # Render panel mein set karna hoga as environment variable
