services:
  - type: worker
    name: firebase-ml-listener
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python firebase_listener.py"
