services:
  - type: web
    name: firebase-listener
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python firebase_listener.py
    envVars:
      - key: FIREBASE_KEY_JSON
        fromDatabase: your_database_key_as_environment_variable
    plan: free
